#!/bin/bash
DIR="~/Scripts" # mainscript location, directory format
CLIPBOARD=$(xclip -selection c -o)
SENDME=$($DIR/mainscript -b :en "${CLIPBOARD}")
SENDME2=$($DIR/mainscript -show-translation n -show-prompt-message n -show-languages n -show-original-dictionary n -show-dictionary n -show-alternatives n -show-original-phonetics y "${CLIPBOARD}")
LANGUAGE=$($DIR/mainscript -id "${CLIPBOARD}" | grep Code | awk '{print $2}')
notify-send --urgency=normal --expire-time=20000 "Translation results" "${SENDME}\n${SENDME2}"
$DIR/mainscript -b -p :${LANGUAGE} "${CLIPBOARD}" > /dev/zero
